<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HandMade.Domain\HandMade.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Addresses\Queries\" />
    <Folder Include="Features\Files\Queries\" />
    <Folder Include="Features\RolesManagement\Commands\" />
    <Folder Include="Features\Shops\Commands\RejectShop\DTOs\" />
    <Folder Include="Features\Shops\Orchestrators\" />
  </ItemGroup>

</Project>
